[tool.poetry]
name = "random-things"
version = "0.1.0"
description = ""
authors = ["Dragonlord1005 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Sphinx = "^4.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
